import os

from cloudpathlib import AnyPath


def is_value_true(value: str, env_var_name: str) -> bool:
    env_var_lower = value.lower()
    if env_var_lower not in ("true", "false", "1", "0"):
        raise ValueError(
            f"Invalid boolean value: {value} for environment variable {env_var_name}"
        )
    return env_var_lower in ("true", "1")


def is_env_true(env_var_name: str) -> bool:
    env_var_value = os.environ[env_var_name]
    return is_value_true(env_var_value, env_var_name)


# The defaults are already ws://, but make the env vars support http:// and https://
STT_IS_GRADIUM = is_env_true("STT_IS_GRADIUM")
KYUTAI_STT_URL = os.environ["KYUTAI_STT_URL"]
TTS_IS_GRADIUM = is_env_true("TTS_IS_GRADIUM")
TTS_SERVER = os.environ["TTS_SERVER"]

KYUTAI_API_KEY = os.environ.get("KYUTAI_API_KEY")

LLM_API_KEY = os.environ["KYUTAI_LLM_API_KEY"]
LLM_URL = os.environ["KYUTAI_LLM_URL"]
LLM_MODEL = os.environ["KYUTAI_LLM_MODEL"]

# Backend runtime mode.
# - "audio": default, uses Opus/VAD server-side STT pipeline.
# - "text_only": backend does not require audio dependencies (no fastrtc).
BACKEND_MODE = os.environ.get("BACKEND_MODE", "audio").strip().lower()

# The shared anonymous account (used by the native app without login) exposes
# its full profile AND conversation history over GET /v1/user/anonymous with
# no authentication. That is fine on a LAN/private deployment, but on a public
# server it leaks the user's conversations (de facto health-related data) to
# anyone. Default is CLOSED (0): you must explicitly opt in with
# ALLOW_ANONYMOUS_USER=1 on a trusted/private network only.
ALLOW_ANONYMOUS_USER = os.environ.get("ALLOW_ANONYMOUS_USER", "0").strip() == "1"
# If None, a dict-based cache will be used instead of Redis

# Redis Configuration for Locking
REDIS_HOST = os.getenv("REDIS_HOST", "localhost")
REDIS_PORT = int(os.getenv("REDIS_PORT", "6379"))
# Full Redis connection URL. Takes precedence over REDIS_HOST/REDIS_PORT when set
# (e.g. a managed Redis like Upstash: "rediss://default:<password>@host:port").
REDIS_URL = os.getenv("REDIS_URL") or f"redis://{REDIS_HOST}:{REDIS_PORT}"
TTS_LOCK_TTL_SECONDS = int(os.getenv("TTS_LOCK_TTL_SECONDS", "30"))
STT_LOCK_TTL_SECONDS = int(os.getenv("STT_LOCK_TTL_SECONDS", "600"))

# Also checked on the frontend, see constant of the same name
MAX_VOICE_FILE_SIZE_MB = 4


SAMPLE_RATE = 24000
SAMPLES_PER_FRAME = 1920
FRAME_TIME_SEC = SAMPLES_PER_FRAME / SAMPLE_RATE  # 0.08
# TODO: make it so that we can read this from the ASR server?
STT_DELAY_SEC = 2

# Number of suggested responses and keywords generated by the LLM per turn.
# Lower values = faster LLM generation and less cognitive load for the user.
NB_RESPONSES = 3
NB_KEYWORDS = 6

USERS_DATA_DIR = AnyPath(os.environ["KYUTAI_USERS_DATA_PATH"])

USERS_AUDIO_DIR = USERS_DATA_DIR / "user_audio"
USERS_AUDIO_DIR.mkdir(parents=True, exist_ok=True)

USERS_SETTINGS_AND_HISTORY_DIR = USERS_DATA_DIR / "user_settings_and_history"
USERS_SETTINGS_AND_HISTORY_DIR.mkdir(parents=True, exist_ok=True)
TTS_VOICE_ID = os.environ.get(
    "TTS_VOICE_ID", "vMYQUSzm6GRkJX6d"
)  # Olivier (fr, masculin)


ALLOW_PASSWORD = is_value_true(
    os.environ.get("ALLOW_PASSWORD", "true") or "true", "ALLOW_PASSWORD"
)
GOOGLE_CLIENT_ID = os.environ.get("GOOGLE_CLIENT_ID", "REPLACE_ME")

# Optional bearer token guarding the Prometheus /metrics endpoint. When set,
# /metrics requires `Authorization: Bearer <token>` and returns 404 otherwise.
# Leave unset for same-origin deployments where Prometheus scrapes the backend
# over the internal network and Traefik blocks external /metrics access. Set it
# on a publicly reachable deployment (e.g. Cloud Run) to keep metrics private.
METRICS_TOKEN = os.environ.get("METRICS_TOKEN", "")

# Origins allowed to call the API cross-origin. Needed when the frontend is
# served from a different origin than the backend (e.g. PWA on Firebase Hosting
# calling the Cloud Run backend). Comma-separated, e.g.
# "https://my-app.web.app,https://my-app.firebaseapp.com".
_DEFAULT_CORS_ORIGINS = ["http://localhost", "http://localhost:3000"]
_extra_cors = os.environ.get("CORS_ALLOW_ORIGINS", "")
CORS_ALLOW_ORIGINS = _DEFAULT_CORS_ORIGINS + [
    origin.strip() for origin in _extra_cors.split(",") if origin.strip()
]
