"""Memory consolidation for InvincibleVoice.

The product goal: a person who can no longer speak must be able to express
themselves with the **same tone** and the **same knowledge** as before. The
naive approach (replay raw conversation history) fails that goal on two
fronts:

1. **Knowledge decays.** Personal facts mentioned in conversation ("I taught
   maths for 20 years", "I'm allergic to penicillin") live only inside the
   last `MAX_PAST_CONVERSATIONS_IN_PROMPT` conversations replayed into the
   prompt. Once they scroll out, they're gone from the LLM's view — the user
   is no longer the same *person* to the assistant.

2. **Tone is learned without context.** The previous `_chosen_style_examples`
   extracted the user's chosen sentences *in isolation*. But tone is a
   relation between what the interlocutor said and how the user replied.
   "Oui, bien sûr" reveals nothing about style without knowing the prompt it
   answered.

This module addresses both by deriving two compact, durable artifacts from
the conversation history, stored alongside the raw history:

- **`ToneProfile`** — a short textual description of *how* the user speaks,
  refreshed periodically by asking the LLM to characterize the style. It is
  cheap (a few hundred tokens) and stable across sessions.

- **`MemoryFact`** — a discrete personal fact extracted from conversations
  ("allergic to penicillin", "has 3 grandchildren"). Facts are accumulated,
  deduplicated and capped so the knowledge base stays bounded.

- **`StyleExchange`** — the user's chosen reply *paired* with the speaker's
  turn it answered, so the LLM learns the relation, not just the words.

These artifacts are injected into the system prompt by `storage.py`, keeping
the user's identity durable regardless of how much raw history scrolls out
of the bounded replay window.

The extraction itself is **non-blocking and fault-tolerant**: it runs after a
conversation is saved and never prevents the user from speaking. If the LLM
is unavailable, the artifacts simply aren't refreshed — the previous ones
remain in place.
"""

from __future__ import annotations

import datetime as dt
import logging
import os

import pydantic

logger = logging.getLogger(__name__)

# --- Bounds (tuneable via env) ------------------------------------------------

# Hard cap on the number of facts retained. Facts are small (one line each),
# but without a cap an active user would grow this indefinitely and inflate
# every prompt. 50 is roughly one personal fact per conversation over a month.
MAX_FACTS = int(os.environ.get("MEMORY_MAX_FACTS", "50"))

# Hard cap on the number of contextual style exchanges retained. Each exchange
# is a (speaker turn, user reply) pair, so they're heavier than facts.
MAX_STYLE_EXCHANGES = int(os.environ.get("MEMORY_MAX_STYLE_EXCHANGES", "15"))

# Hard cap on the total number of conversations persisted server-side. The
# prompt only ever replays a bounded window, so keeping thousands of old
# conversations just makes `save()`/`load()` slower and the JSON bigger.
# Older conversations are pruned (their facts/style are already distilled).
MAX_STORED_CONVERSATIONS = int(os.environ.get("MEMORY_MAX_STORED_CONVERSATIONS", "200"))

# Hard cap on a single document's content injected into the prompt, in
# characters. A user pasting a 50k-character document would otherwise blow up
# latency and cost on every single turn.
MAX_DOCUMENT_CHARS_IN_PROMPT = int(
    os.environ.get("MEMORY_MAX_DOCUMENT_CHARS_IN_PROMPT", "4000")
)

# Only conversations with at least this many user-chosen messages are worth
# mining for style/knowledge. A one-message exchange carries little signal.
MIN_MESSAGES_FOR_EXTRACTION = 2


# --- Data models --------------------------------------------------------------


class MemoryFact(pydantic.BaseModel):
    """A single durable personal fact extracted from conversations."""

    text: str
    # When the fact was first observed. Used for dedup ordering and display.
    observed_at: dt.datetime


class StyleExchange(pydantic.BaseModel):
    """A speaker turn paired with the user's chosen reply.

    The user's reply is the `WriterMessage` they selected; the speaker turn is
    the `SpeakerMessage`(s) immediately preceding it in the same conversation.
    Kept together so the LLM learns *how* the user reacts, not just *what*
    they say in a vacuum.
    """

    speaker_turn: str
    user_reply: str


class ToneProfile(pydantic.BaseModel):
    """A compact textual characterization of the user's speaking style.

    Generated by asking the LLM to summarize the user's voice from their past
    chosen replies. Stored as plain text because it is injected verbatim into
    the system prompt.
    """

    # None until the first profile has been generated.
    summary: str | None = None
    # When the profile was last refreshed. Used to decide whether it's stale.
    updated_at: dt.datetime | None = None


class UserMemory(pydantic.BaseModel):
    """The durable, distilled memory layer for one user.

    Lives next to `UserSettings` inside the user's JSON file. Everything here
    is *derived* from conversations — it is a cache, not a source of truth —
    so it can always be rebuilt from history if corrupted.
    """

    facts: list[MemoryFact] = pydantic.Field(default_factory=list)
    style_exchanges: list[StyleExchange] = pydantic.Field(default_factory=list)
    tone_profile: ToneProfile = pydantic.Field(default_factory=ToneProfile)
    # Conversations (start_time ISO strings) already folded in by the
    # *synchronous* style pass at cleanup. Prevents re-pairing the same
    # exchanges on every save.
    processed_conversations: list[str] = pydantic.Field(default_factory=list)
    # Conversations already mined by the *asynchronous* LLM pass (fact
    # extraction + tone profile). Kept SEPARATE from `processed_conversations`
    # on purpose: the sync style pass marks a conversation processed the moment
    # the session ends, so if both passes shared one marker the background LLM
    # pass would find every conversation already "processed" and never extract
    # a single fact. Two markers let the two passes advance independently.
    facts_processed_conversations: list[str] = pydantic.Field(default_factory=list)
    # Conversations mined by the LLM pass since the tone profile was last
    # refreshed. Regenerating the profile on every single conversation would be
    # wasteful, so we batch it — and this counter is cumulative *across
    # sessions*, because in steady state only one conversation is mined per
    # session (a per-run counter would never reach the threshold).
    conversations_since_tone_refresh: int = 0

    def add_fact(self, text: str, when: dt.datetime) -> None:
        text = text.strip()
        if not text:
            return
        # Dedup on normalized text: case-insensitive, whitespace-collapsed,
        # trailing punctuation stripped — so "Allergique." and "allergique"
        # are treated as the same fact.
        normalized = self._normalize_fact(text)
        existing = {self._normalize_fact(f.text) for f in self.facts}
        if normalized in existing:
            return
        self.facts.append(MemoryFact(text=text, observed_at=when))
        # Keep the most recent MAX_FACTS (drop oldest when over capacity).
        if len(self.facts) > MAX_FACTS:
            self.facts = self.facts[-MAX_FACTS:]

    @staticmethod
    def _normalize_fact(text: str) -> str:
        collapsed = " ".join(text.lower().split())
        return collapsed.rstrip(".,;:!?")

    def add_style_exchange(self, speaker_turn: str, user_reply: str) -> None:
        speaker_turn = speaker_turn.strip()
        user_reply = user_reply.strip()
        if not speaker_turn or not user_reply:
            return
        # Skip trivially short replies — "Oui" alone teaches nothing about tone
        # and would crowd out more expressive examples.
        if len(user_reply.split()) < 2:
            return
        exchange = StyleExchange(speaker_turn=speaker_turn, user_reply=user_reply)
        self.style_exchanges.append(exchange)
        if len(self.style_exchanges) > MAX_STYLE_EXCHANGES:
            self.style_exchanges = self.style_exchanges[-MAX_STYLE_EXCHANGES:]

    def mark_processed(self, conversation_start_time: dt.datetime) -> None:
        """Mark a conversation folded in by the synchronous style pass."""
        self._mark(self.processed_conversations, conversation_start_time)

    def is_processed(self, conversation_start_time: dt.datetime) -> bool:
        return conversation_start_time.isoformat() in self.processed_conversations

    def mark_facts_processed(self, conversation_start_time: dt.datetime) -> None:
        """Mark a conversation mined by the LLM fact/tone pass."""
        self._mark(self.facts_processed_conversations, conversation_start_time)

    def is_facts_processed(self, conversation_start_time: dt.datetime) -> bool:
        return (
            conversation_start_time.isoformat() in self.facts_processed_conversations
        )

    @staticmethod
    def _mark(bucket: list[str], when: dt.datetime) -> None:
        # Bound each marker list: it only needs to cover recent history since
        # older conversations are pruned from storage anyway.
        key = when.isoformat()
        if key not in bucket:
            bucket.append(key)
            if len(bucket) > MAX_STORED_CONVERSATIONS:
                del bucket[:-MAX_STORED_CONVERSATIONS]


# --- Extraction (synchronous, history-only) -----------------------------------
#
# The first pass is deterministic and requires no LLM: we pair each user
# reply with the speaker turn it answered, and we extract candidate facts.
# The LLM-driven refinement (tone profile generation, fact deduplication by
# meaning) is layered on top in the async section below.


def extract_style_exchanges_from_conversation(
    messages: list,
) -> list[StyleExchange]:
    """Pair each user-chosen reply with the speaker turn(s) immediately before it.

    `messages` is a list of `SpeakerMessage | WriterMessage`. We accumulate
    consecutive speaker lines into one `speaker_turn` (a real conversation is
    not one-line ping-pong), and emit an exchange when a `WriterMessage`
    arrives.
    """
    from backend.app_types import SpeakerMessage, WriterMessage

    exchanges: list[StyleExchange] = []
    pending_speaker_lines: list[str] = []

    for message in messages:
        if isinstance(message, SpeakerMessage):
            text = message.content.strip()
            if text:
                pending_speaker_lines.append(text)
        elif isinstance(message, WriterMessage):
            reply = message.content.strip()
            if not reply:
                pending_speaker_lines.clear()
                continue
            if pending_speaker_lines:
                speaker_turn = " ".join(pending_speaker_lines)
                exchanges.append(
                    StyleExchange(speaker_turn=speaker_turn, user_reply=reply)
                )
            pending_speaker_lines.clear()

    return exchanges


def has_minimal_signal(messages: list) -> bool:
    """Whether a conversation is worth mining at all.

    We need at least one user-chosen reply (a `WriterMessage`) to learn
    anything about style, and at least one speaker turn to give it context.
    """
    from backend.app_types import SpeakerMessage, WriterMessage

    has_writer = any(isinstance(m, WriterMessage) for m in messages)
    has_speaker = any(isinstance(m, SpeakerMessage) for m in messages)
    return has_writer and has_speaker and len(messages) >= MIN_MESSAGES_FOR_EXTRACTION


def update_memory_from_conversation(
    memory: UserMemory, conversation, now: dt.datetime | None = None
) -> bool:
    """Fold one conversation into the durable memory, synchronously.

    Extracts contextual style exchanges. Fact extraction is LLM-driven and
    handled separately. Returns True if anything changed.

    Idempotent: calling it twice on the same conversation is a no-op.
    """
    if now is None:
        now = dt.datetime.now(dt.timezone.utc)

    if memory.is_processed(conversation.start_time):
        return False

    messages = conversation.messages
    if not has_minimal_signal(messages):
        memory.mark_processed(conversation.start_time)
        return False

    changed = False
    for exchange in extract_style_exchanges_from_conversation(messages):
        before = len(memory.style_exchanges)
        memory.add_style_exchange(exchange.speaker_turn, exchange.user_reply)
        if len(memory.style_exchanges) > before:
            changed = True

    memory.mark_processed(conversation.start_time)
    return changed


def prune_conversations(conversations: list) -> list:
    """Cap the number of stored conversations, keeping the most recent.

    Older conversations are dropped *after* their facts and style have been
    distilled into `UserMemory`, so no knowledge is lost — only the raw,
    already-summarized transcript is reclaimed.
    """
    if len(conversations) <= MAX_STORED_CONVERSATIONS:
        return conversations
    return conversations[-MAX_STORED_CONVERSATIONS:]


# --- Relevance-based retrieval ------------------------------------------------
#
# The prompt replays a bounded window of past conversations. Chronological
# recency is the default, but a conversation about the *same topic* as the
# current one is often more useful than a more recent but unrelated one.
# A full vector store would be overkill here (and would add a dependency),
# so we use lightweight keyword overlap: tokenize the current conversation
# and each candidate, score by Jaccard-like overlap on meaningful tokens.

# Tokens shorter than this are ignored (stopwords like "le", "la", "un").
_MIN_TOKEN_LEN = 4
# French+English stopwords filtered out so they don't dominate the overlap.
_STOPWORDS = frozenset(
    {
        # French
        "avec",
        "alors",
        "aussi",
        "autre",
        "avant",
        "avoir",
        "bien",
        "cette",
        "comme",
        "dans",
        "depuis",
        "dont",
        "elle",
        "encore",
        "être",
        "faire",
        "faut",
        "fort",
        "ici",
        "leur",
        "mais",
        "meme",
        "moins",
        "nous",
        "parce",
        "pendant",
        "plus",
        "pour",
        "pourquoi",
        "quand",
        "quel",
        "quelle",
        "quels",
        "quelles",
        "sans",
        "seul",
        "sont",
        "sous",
        "tant",
        "tes",
        "tout",
        "toutes",
        "tres",
        "toutefois",
        "veux",
        "votre",
        "vous",
        "etat",
        "etais",
        "etait",
        "etre",
        "leurs",
        "mes",
        "ses",
        "ces",
        "des",
        "les",
        "une",
        "aux",
        "sur",
        "par",
        "que",
        "qui",
        "dan",
        "apres",
        "chez",
        "donc",
        "entre",
        "jusqu",
        "non",
        "oui",
        "cela",
        # French discourse fillers (high frequency, low discriminative value)
        "aujourdhui",
        "aujourd",
        "hui",
        "toujours",
        "maintenant",
        "quelque",
        "quelques",
        "homme",
        "femme",
        "autres",
        # English
        "that",
        "this",
        "with",
        "from",
        "have",
        "they",
        "them",
        "were",
        "been",
        "will",
        "would",
        "could",
        "should",
        "there",
        "their",
        "what",
        "when",
        "which",
        "your",
        "about",
        "into",
        "some",
        "than",
        "then",
        "also",
        "just",
        "very",
        "much",
        "many",
        "such",
        "only",
        "back",
        "today",
        "always",
        "something",
        "someone",
        "every",
    }
)

# Prefix length for naive stemming. Tokens of 6+ characters are reduced to
# their first 5 characters so that "jardin", "jardinage", "jardiner" all
# collapse to "jardi" — a cheap way to match word families without a
# dependency on a full stemmer. 5 is long enough to stay discriminative
# ("tomat" vs "terre") but short enough to unify inflections.
_STEM_PREFIX = 5
_STEM_MIN_LEN = 6


def _tokenize(text: str) -> set[str]:
    """Lowercase, alphanumeric tokens, stopwords removed, lightly stemmed.

    Stemming is prefix-based (first 5 chars for words of 6+ chars) so word
    families ("jardin" / "jardinage") match — critical for relevance between
    French conversations that may use different forms of the same root.
    """
    tokens: set[str] = set()
    current: list[str] = []
    for char in text.lower():
        if char.isalnum():
            current.append(char)
        else:
            if current:
                token = "".join(current)
                if len(token) >= _MIN_TOKEN_LEN and token not in _STOPWORDS:
                    if len(token) >= _STEM_MIN_LEN:
                        token = token[:_STEM_PREFIX]
                    tokens.add(token)
                current = []
    if current:
        token = "".join(current)
        if len(token) >= _MIN_TOKEN_LEN and token not in _STOPWORDS:
            if len(token) >= _STEM_MIN_LEN:
                token = token[:_STEM_PREFIX]
            tokens.add(token)
    return tokens


def _conversation_tokens(conversation) -> set[str]:
    """All meaningful tokens across a conversation's messages."""
    tokens: set[str] = set()
    for message in conversation.messages:
        tokens |= _tokenize(message.content)
    return tokens


def select_relevant_past_conversations(
    conversations: list,
    current_conversation,
    max_count: int,
) -> list:
    """Pick the most topically-relevant past conversations for the current one.

    Always excludes the current conversation itself. Returns up to `max_count`
    conversations ordered by descending relevance; ties break to recency.

    The goal is "same knowledge, same tone": if the user is talking about
    gardening today, a past gardening conversation is more useful than a
    more recent but unrelated one, even if both are within the chronological
    window. We still respect recency as a tie-breaker so very old
    conversations don't dominate.
    """
    if not conversations or max_count <= 0:
        return []

    current_tokens = _conversation_tokens(current_conversation)
    if not current_tokens:
        # No signal to match on: fall back to pure recency.
        return [c for c in conversations[-(max_count + 1) : -1] if len(c.messages) > 0][
            :max_count
        ]

    # Score every other conversation by token overlap with the current one.
    # We iterate oldest-to-newest so equal scores keep the more recent one.
    scored: list[tuple[float, int, object]] = []
    for index, conversation in enumerate(conversations):
        if conversation is current_conversation or len(conversation.messages) == 0:
            continue
        tokens = _conversation_tokens(conversation)
        if not tokens:
            continue
        overlap = len(current_tokens & tokens)
        union = len(current_tokens | tokens)
        score = overlap / union if union else 0.0
        # Only keep conversations that share at least one meaningful token;
        # a 0-overlap conversation adds noise, not context.
        if score > 0.0:
            scored.append((score, index, conversation))

    scored.sort(key=lambda item: (-item[0], -item[1]))
    selected = [c for _, _, c in scored[:max_count]]
    # If relevance yielded fewer than asked, top up with the most recent
    # non-empty conversations not already selected.
    if len(selected) < max_count:
        selected_ids = {id(c) for c in selected}
        for conversation in reversed(conversations):
            if len(selected) >= max_count:
                break
            if (
                conversation is current_conversation
                or len(conversation.messages) == 0
                or id(conversation) in selected_ids
            ):
                continue
            selected.append(conversation)
            selected_ids.add(id(conversation))
    return selected
